# docker-compose.yml
version: '3'
services:
  composer:
    image: composer:2.8.1
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    restart: never
  phpunit:
    image: php:8.2.24
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit