services:
  composer:
    image: composer:2.8.1
    volumes:
      - .:/app
    restart: never
  phpunit:
    image: php:8.2.24
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit