name: Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Composer Init
        uses: php-actions/composer@v6
      - run: |
          echo "Composer dependencies have been installed"

      - name: Run Tests
        run: |
          vendor/bin/phpunit --stop-on-failure

      - name: PHPStan Analysis
        run: |
          vendor/bin/phpstan anatlyse --configuration=phpstan.neon